---
# Universal Settings
 AWS_REGION:
# Defines what our client should be capable of
# Options: IAM, EC2, S3, AS
 FUNCTIONALITY:
  - EC2
  - S3

# IAM Settings
 IAM_USER_NAME: VALUE_NOT_SET
 IAM_USER_TAGS: VALUE_NOT_SET
 IAM_USER_TAGS_VALUE: VALUE_NOT_SET
 IAM_USER_TAGS_KEY: VALUE_NOT_SET

# EC2 Settings
 EC2_INSTANCE_TYPE: VALUE_NOT_SET
 EC2_AMI_ID: VALUE_NOT_SET
 EC2_KEY_NAME: VALUE_NOT_SET
 EC2_SECURITY_GROUP: VALUE_NOT_SET
 EC2_SUBNET_ID: VALUE_NOT_SET
 EC2_IP_ADDRESS: VALUE_NOT_SET
 EC2_INSTANCE_NAME: VALUE_NOT_SET
 EC2_INSTANCE_TAGS: VALUE_NOT_SET
 EC2_INSTANCE_TAGS_VALUE: VALUE_NOT_SET
 EC2_INSTANCE_TAGS_KEY: VALUE_NOT_SET

# S3 Settings
 S3_BUCKET_NAME: VALUE_NOT_SET
 S3_BUCKET_TAGS: VALUE_NOT_SET
 S3_BUCKET_TAGS_VALUE: VALUE_NOT_SET
 S3_BUCKET_TAGS_KEY: VALUE_NOT_SET

# AS Settings
 WORKER_MINIMUM: VALUE_NOT_SET
 WORKER_MAXIMUM: VALUE_NOT_SET


...
