---
# Universal Settings
 AWS_REGION:
# Defines what our client should be capable of
 FUNCTIONALITY:
  - EC2
  - S3

# IAM Settings
 IAM_USER_NAME: TODO
 IAM_USER_TAGS: TODO
 IAM_USER_TAGS_VALUE: TODO
 IAM_USER_TAGS_KEY: TODO

# EC2 Settings
 EC2_INSTANCE_TYPE: TODO
 EC2_AMI_ID: TODO
 EC2_KEY_NAME: TODO
 EC2_SECURITY_GROUP: TODO
 EC2_SUBNET_ID: TODO
 EC2_IP_ADDRESS: TODO
 EC2_INSTANCE_NAME: TODO
 EC2_INSTANCE_TAGS: TODO
 EC2_INSTANCE_TAGS_VALUE: TODO
 EC2_INSTANCE_TAGS_KEY: TODO

# S3 Settings
 S3_BUCKET_NAME: TODO
 S3_BUCKET_TAGS: TODO
 S3_BUCKET_TAGS_VALUE: TODO
 S3_BUCKET_TAGS_KEY: TODO

# AutoScaler Settings
 WORKER_MINIMUM: TODO
 WORKER_MAXIMUM: TODO


...
